  var imageURLs = [
       "inspire/@pixelart/_waneella-001.gif"     , "inspire/@pixelart/_waneella-002.gif"
     , "inspire/@pixelart/_waneella-003.gif"     , "inspire/@pixelart/_waneella-004.gif"
     , "inspire/@pixelart/_waneella-005.gif"     , "inspire/@pixelart/_waneella-006.gif"
     , "inspire/@pixelart/_waneella-007.gif"     , "inspire/@pixelart/_waneella-008.gif"
     , "inspire/@pixelart/_waneella-009.gif"     , "inspire/@pixelart/_waneella-010.gif"
     , "inspire/@pixelart/_waneella-011.gif"     , "inspire/@pixelart/_waneella-012.gif"
     , "inspire/@pixelart/_waneella-013.gif"     , "inspire/@pixelart/_waneella-014.gif"
     , "inspire/@pixelart/_waneella-015.gif"     , "inspire/@pixelart/_waneella-016.gif"
     , "inspire/@pixelart/_waneella-017.gif"     , "inspire/@pixelart/_waneella-018.gif"
     , "inspire/@pixelart/_waneella-019.gif"     , "inspire/@pixelart/_waneella-020.gif"
     , "inspire/@pixelart/_waneella-021.gif"     , "inspire/@pixelart/_waneella-022.gif"
     , "inspire/@pixelart/_waneella-023.gif"     

     , "inspire/@pixelart/mabius-01.png"     , "inspire/@pixelart/mabius-02.png"
     , "inspire/@pixelart/mabius-03.png"     , "inspire/@pixelart/mabius-04.png"
     , "inspire/@pixelart/mabius-05.png"     , "inspire/@pixelart/mabius-06.png"
     , "inspire/@pixelart/mabius-07.png"     , "inspire/@pixelart/mabius-08.png"
     , "inspire/@pixelart/mabius-09.png"     , "inspire/@pixelart/mabius-10.png"
     , "inspire/@pixelart/mabius-11.png"     , "inspire/@pixelart/mabius-12.png"
     , "inspire/@pixelart/mabius-13.png"     , "inspire/@pixelart/mabius-14.png"
     , "inspire/@pixelart/mabius-15.png"     , "inspire/@pixelart/mabius-16.png"
     , "inspire/@pixelart/mabius-17.png"     , "inspire/@pixelart/mabius-18.png"
     , "inspire/@pixelart/mabius-19.png"     , "inspire/@pixelart/mabius-20.png"
     , "inspire/@pixelart/mabius-21.png"     , "inspire/@pixelart/mabius-22.png"
     , "inspire/@pixelart/mabius-23.png"     , "inspire/@pixelart/mabius-24.png"
     , "inspire/@pixelart/mabius-25.png"     , "inspire/@pixelart/mabius-26.png"
     , "inspire/@pixelart/mabius-27.png"     , "inspire/@pixelart/mabius-28.png"
     , "inspire/@pixelart/mabius-29.png"     , "inspire/@pixelart/mabius-30.png"
     , "inspire/@pixelart/mabius-31.png"     , "inspire/@pixelart/mabius-32.png"
     , "inspire/@pixelart/mabius-33.png"     , "inspire/@pixelart/mabius-34.png"
     , "inspire/@pixelart/mabius-35.png"     , "inspire/@pixelart/mabius-36.png"
     , "inspire/@pixelart/mabius-37.png"     , "inspire/@pixelart/mabius-38.png"
     , "inspire/@pixelart/mabius-39.png"     , "inspire/@pixelart/mabius-30.png"
     , "inspire/@pixelart/mabius-41.png"     , "inspire/@pixelart/mabius-42.png"
     , "inspire/@pixelart/mabius-43.png"     , "inspire/@pixelart/mabius-44.png"
     , "inspire/@pixelart/mabius-45.png"     , "inspire/@pixelart/mabius-46.png"
     , "inspire/@pixelart/mabius-47.png"     , "inspire/@pixelart/mabius-48.png"
     , "inspire/@pixelart/mabius-49.png"     , "inspire/@pixelart/mabius-40.png"
     , "inspire/@pixelart/mabius-51.png"     , "inspire/@pixelart/mabius-52.png"
     , "inspire/@pixelart/mabius-53.png"     , "inspire/@pixelart/mabius-54.png"
     , "inspire/@pixelart/mabius-55.png"     , "inspire/@pixelart/mabius-56.png"
     , "inspire/@pixelart/mabius-57.png"     , "inspire/@pixelart/mabius-58.png"
     , "inspire/@pixelart/mabius-59.png"     , "inspire/@pixelart/mabius-50.png"
     , "inspire/@pixelart/mabius-61.png"     , "inspire/@pixelart/mabius-62.png"
     , "inspire/@pixelart/mabius-63.png"     , "inspire/@pixelart/mabius-64.png"
     , "inspire/@pixelart/mabius-65.png"     , "inspire/@pixelart/mabius-66.png"
     , "inspire/@pixelart/mabius-67.png"     , "inspire/@pixelart/mabius-68.png"
     , "inspire/@pixelart/mabius-69.png"     , "inspire/@pixelart/mabius-60.png"
     
     , "inspire/@pixelart/omegachainoboy-01.png"     , "inspire/@pixelart/omegachainoboy-02.png"
     , "inspire/@pixelart/omegachainoboy-03.png"     , "inspire/@pixelart/omegachainoboy-04.png"
     , "inspire/@pixelart/omegachainoboy-05.png"     , "inspire/@pixelart/omegachainoboy-06.png"
     , "inspire/@pixelart/omegachainoboy-07.png"     , "inspire/@pixelart/omegachainoboy-08.png"
     , "inspire/@pixelart/omegachainoboy-09.png"     , "inspire/@pixelart/omegachainoboy-10.png"
     , "inspire/@pixelart/omegachainoboy-11.png"     , "inspire/@pixelart/omegachainoboy-12.png"
     , "inspire/@pixelart/omegachainoboy-13.png"     , "inspire/@pixelart/omegachainoboy-14.png"
     , "inspire/@pixelart/omegachainoboy-15.png"     , "inspire/@pixelart/omegachainoboy-16.png"
     , "inspire/@pixelart/omegachainoboy-17.png"     , "inspire/@pixelart/omegachainoboy-18.png"
     , "inspire/@pixelart/omegachainoboy-19.png"     , "inspire/@pixelart/omegachainoboy-20.png"
     , "inspire/@pixelart/omegachainoboy-21.png"     , "inspire/@pixelart/omegachainoboy-22.png"
     , "inspire/@pixelart/omegachainoboy-23.png"     , "inspire/@pixelart/omegachainoboy-24.png"
     , "inspire/@pixelart/omegachainoboy-25.png"     , "inspire/@pixelart/omegachainoboy-26.png"
     , "inspire/@pixelart/omegachainoboy-27.png"     , "inspire/@pixelart/omegachainoboy-28.png"
     , "inspire/@pixelart/omegachainoboy-29.png"     , "inspire/@pixelart/omegachainoboy-30.png"
     , "inspire/@pixelart/omegachainoboy-31.png"     , "inspire/@pixelart/omegachainoboy-32.png"
     , "inspire/@pixelart/omegachainoboy-33.png"     , "inspire/@pixelart/omegachainoboy-34.png"
     , "inspire/@pixelart/omegachainoboy-35.png"     , "inspire/@pixelart/omegachainoboy-36.png"
     , "inspire/@pixelart/omegachainoboy-37.png"     , "inspire/@pixelart/omegachainoboy-38.png"
     , "inspire/@pixelart/omegachainoboy-39.png"     , "inspire/@pixelart/omegachainoboy-30.png"
     , "inspire/@pixelart/omegachainoboy-41.png"     , "inspire/@pixelart/omegachainoboy-42.png"
     , "inspire/@pixelart/omegachainoboy-43.png"     , "inspire/@pixelart/omegachainoboy-44.png"
     , "inspire/@pixelart/omegachainoboy-45.png"     , "inspire/@pixelart/omegachainoboy-46.png"
     , "inspire/@pixelart/omegachainoboy-47.png"     , "inspire/@pixelart/omegachainoboy-48.png"
     , "inspire/@pixelart/omegachainoboy-49.png"     , "inspire/@pixelart/omegachainoboy-40.png"
     , "inspire/@pixelart/omegachainoboy-51.png"     , "inspire/@pixelart/omegachainoboy-52.png"
     , "inspire/@pixelart/omegachainoboy-53.png"     , "inspire/@pixelart/omegachainoboy-54.png"
     , "inspire/@pixelart/omegachainoboy-55.png"     

     , "inspire/@pixelart/tw-pixelflag-4a0f-84cf-d50366638816.png"     , "inspire/@pixelart/tw-pixelflag_ddi25fn-pre.jpg"
     , "inspire/@pixelart/tw-pixelflag_ddk4tvt-pre.png"                , "inspire/@pixelart/tw-pixelflag_de5sy0y-pre.jpg"
     , "inspire/@pixelart/tw-pixelflag_E7ZOM6GVEAUw_yN.png"            , "inspire/@pixelart/tw-pixelflag_4a0fa.png"
     , "inspire/@pixelart/tw-pixelflag_ddjgvpu-pre.png"                , "inspire/@pixelart/tw-pixelflag_ddkjg72-pre.jpg"
     , "inspire/@pixelart/tw-pixelflag_de5sy22-pre.jpg"                , "inspire/@pixelart/tw-pixelflag_E9TYmrkVIAE7rYB.png"
     , "inspire/@pixelart/tw-pixelflag_4a0f.png"                       , "inspire/@pixelart/tw-pixelflag_ddjiont-pre.png"
     , "inspire/@pixelart/tw-pixelflag_ddkjh76-pre.jpg"                , "inspire/@pixelart/tw-pixelflag_de65grq-pre.jpg"
     , "inspire/@pixelart/tw-pixelflag-EtnejpYUcAIEhau.jpg"            , "inspire/@pixelart/tw-pixelflag-D5KgVXfVUAAc09q.png"
     , "inspire/@pixelart/tw-pixelflag_ddjk819-pre.jpg"                , "inspire/@pixelart/tw-pixelflag_ddkjh9m-pre.png"
     , "inspire/@pixelart/tw-pixelflag_de9lsna-pre.jpg"                , "inspire/@pixelart/tw-pixelflag-ExKv7LAUYAYGBCn.png"
     , "inspire/@pixelart/tw-pixelflag_dccrr8r-pre.png"                , "inspire/@pixelart/tw-pixelflag_ddjlrur-pre.jpg"
     , "inspire/@pixelart/tw-pixelflag_ddlw61v-pre.jpg"                , "inspire/@pixelart/tw-pixelflag_dedj8wx-pre.jpg"
     , "inspire/@pixelart/tw-pixelflag-FH2EUNIaAAAKj3U.png"            , "inspire/@pixelart/tw-pixelflag_dccrser-pre.png"
     , "inspire/@pixelart/tw-pixelflag_ddjp92i-pre.png"                , "inspire/@pixelart/tw-pixelflag_ddmwck2-pre.jpg"
     , "inspire/@pixelart/tw-pixelflag-Df908fdVMAAYWqd.png"            , "inspire/@pixelart/tw-pixelflag-FM5_SE9acAAndsi.png"
     , "inspire/@pixelart/tw-pixelflag_dccrsj1-pre.png"                , "inspire/@pixelart/tw-pixelflag_ddjqui2-pre.jpg"
     , "inspire/@pixelart/tw-pixelflag_ddmytoc-pre.jpg"                , "inspire/@pixelart/tw-pixelflag-E2PB1uiVcAA9Oio.png"
     , "inspire/@pixelart/tw-pixelflag-FQ2krQeacAA4Xhf.png"            , "inspire/@pixelart/tw-pixelflag_dccrso7-pre.jpg"
     , "inspire/@pixelart/tw-pixelflag_ddjwgb8-pre.png"                , "inspire/@pixelart/tw-pixelflag_ddsok8s-pre.jpg"
     , "inspire/@pixelart/tw-pixelflag-E48kYzOUcAAc3ya.png"            , "inspire/@pixelart/tw-pixelflag--L8EGrSKi0W5xkbX.mp4"
     , "inspire/@pixelart/tw-pixelflag_ddhtczy-pre.png"                , "inspire/@pixelart/tw-pixelflag_ddjyt32-pre.png"
     , "inspire/@pixelart/tw-pixelflag_dduw29s-pre.jpg"                , "inspire/@pixelart/tw-pixelflag-E5CnsMjVcAIgkBt.png"
     , "inspire/@pixelart/tw-pixelflag-__NNb5UYAEWRnK.jpg"             , "inspire/@pixelart/tw-pixelflag_ddhuvms-pre.png"
     , "inspire/@pixelart/tw-pixelflag_ddk003g-pre.png"                , "inspire/@pixelart/tw-pixelflag_ddykywi-pre.jpg"
     , "inspire/@pixelart/tw-pixelflag-E5CoCdgVEAAbw7W.png"            , "inspire/@pixelart/tw-pixelflag_ddi0r7w-pre.png"
     , "inspire/@pixelart/tw-pixelflag_ddk2bd5-pre.jpg"                , "inspire/@pixelart/tw-pixelflag_de285jw-pre.jpg"
     , "inspire/@pixelart/tw-pixelflag-E6AeVa9UcAIsJrn.png"




    ];
    
  function getImageTag() {
    var img = '<img src=\"';
    var randomIndex = Math.floor(Math.random() * imageURLs.length);
    img += imageURLs[randomIndex];
    img += '\" alt=\"Some alt text\" width=300 />';
    return img;
  }
