  var imageURLs = [
       "inspire/@CARTOONS/@gif%20animations/_yui-01.gif"     , "inspire/@CARTOONS/@gif%20animations/_yui-02.gif"
     , "inspire/@CARTOONS/@gif%20animations/_yui-03.gif"     , "inspire/@CARTOONS/@gif%20animations/_yui-04.gif"
     , "inspire/@CARTOONS/@gif%20animations/_yui-05.gif"     , "inspire/@CARTOONS/@gif%20animations/_yui-06.gif"
     , "inspire/@CARTOONS/@gif%20animations/_yui-07.gif"     , "inspire/@CARTOONS/@gif%20animations/_yui-08.gif"
     , "inspire/@CARTOONS/@gif%20animations/_yui-09.gif"     , "inspire/@CARTOONS/@gif%20animations/_yui-10.gif"
     , "inspire/@CARTOONS/@gif%20animations/_yui-11.gif"     , "inspire/@CARTOONS/@gif%20animations/_yui-12.gif"
     , "inspire/@CARTOONS/@gif%20animations/_yui-13.gif"     , "inspire/@CARTOONS/@gif%20animations/_yui-14.gif"
     , "inspire/@CARTOONS/@gif%20animations/_yui-15.gif"     , "inspire/@CARTOONS/@gif%20animations/_yui-16.gif"
     , "inspire/@CARTOONS/@gif%20animations/_yui-17.gif"     , "inspire/@CARTOONS/@gif%20animations/_yui-18.gif"
     , "inspire/@CARTOONS/@gif%20animations/_yui-19.gif"     , "inspire/@CARTOONS/@gif%20animations/_yui-20.gif"
     , "inspire/@CARTOONS/@gif%20animations/_yui-21.gif"     , "inspire/@CARTOONS/@gif%20animations/_yui-22.gif"
     , "inspire/@CARTOONS/@gif%20animations/_yui-23.gif"     , "inspire/@CARTOONS/@gif%20animations/_yui-24.gif"
     , "inspire/@CARTOONS/@gif%20animations/_yui-12.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-001-shine.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-002-attack.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-003-smoke.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-004-runcycle.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-006-topdown-runcycle.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-008-glitch.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-009-progression.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-010-water.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-011-firetut.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-012-seamless.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-013-vegetation1.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-014-skulls.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-015-char-design.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-016-planning.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-017-pixelmovement.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-018-explosions.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-019-machines.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-020-parallax.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-021-rendertricks.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-022-easing.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-023-process.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-024-ruins.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-025-propulsion.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-026-darkmagic.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-027-portraits.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-028-magic.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-029-wings.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-030-slime.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-031-rocks.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-032-vegetation.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-033-fund02.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-034-city-back.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-035-blur.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-036-facestretch.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-037-metal.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-037-squash.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-038-bullets.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-039-idle.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-040-tiles.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-041-blood.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-042-fabric.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-043-triggers.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-044-clouds.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-045-shading.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-046-horsecycle.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-047-outlines.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-048-walkcycle.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-049-stars.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-050-wind01.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-051-1bit.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-052-9slice.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-053-darkness.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-054-breakingobjs.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-055-modular.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-056-cuteness.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-057-vegetation3.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-058-sand.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-059-Death.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-05-fund01.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-060-indoors.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-061-wallclimb.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-062-roll.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-063-spaceships.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-064-snow.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-065-topdown-houses.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-066-defend-takehit.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-067-holo.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-068-Firearms.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-069-Gems.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-070-lighting.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-071-scale.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-072-wood.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-073-swords.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-074-topdownwalkcycle.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pm-076-firearms.gif"
     , "inspire/@CARTOONS/@gif%20animations/___pmaqualcosa.gif"
     , "inspire/masayume/pub/CATS.gif"     	     , "inspire/masayume/pub/chill-the-lion.gif"     
     , "inspire/masayume/pub/czarmichael.gif"     , "inspire/masayume/pub/dormouse.gif"     
     , "inspire/masayume/pub/evan_palmer.gif"     , "inspire/masayume/pub/florian.gif"     
     , "inspire/masayume/pub/ghibli.gif"          , "inspire/masayume/pub/heri-shirato.gif"     
     , "inspire/masayume/pub/howardlyon.gif"      , "inspire/masayume/pub/jet-engine.gif"     
     , "inspire/masayume/pub/jigoku2.gif"         , "inspire/masayume/pub/jplosz.gif"     
     , "inspire/masayume/pub/mr.whaite.gif"       , "inspire/masayume/pub/Mona-Lisa-gif.gif"     
     , "inspire/masayume/pub/motionaddicts.gif"   , "inspire/masayume/pub/lostinthetrainstation.gif"     
     , "inspire/masayume/pub/cognitivebias.gif"   , "inspire/masayume/pub/cole_otts.gif"     
     , "inspire/masayume/pub/pizurny.gif"     	, "inspire/masayume/pub/combinedgifs.gif"     
     , "inspire/masayume/pub/pongdrian.gif"       , "inspire/masayume/pub/pop.gif"     
     , "inspire/masayume/pub/RGBL01.gif"     	, "inspire/masayume/pub/procgen.gif"     
     , "inspire/masayume/pub/quiet.gif"           , "inspire/masayume/pub/revengwon.gif"     
     , "inspire/masayume/pub/robin_dawey.gif"     , "inspire/masayume/pub/rmock.gif"     
     , "inspire/masayume/pub/sheenwip.gif"        , "inspire/masayume/pub/sholim.gif"     
     , "inspire/masayume/pub/smudge.gif"          , "inspire/masayume/pub/chun_li_punch_color.gif"     
     , "inspire/masayume/pub/spine.gif"           , "inspire/masayume/pub/stereoview.gif"     
     , "inspire/masayume/pub/szakaly.gif"         , "inspire/masayume/pub/tenoritaiga.gif"     
     , "inspire/masayume/pub/TRON.gif"            , "inspire/masayume/pub/theblackhole.gif"     
     , "inspire/masayume/pub/tinoue.gif"          , "inspire/masayume/pub/tokyoiter.gif"     
     , "inspire/masayume/pub/totorojump.gif"      , "inspire/masayume/pub/tensors_flowing.gif"     
     , "inspire/masayume/pub/tumblrmath.gif"      , "inspire/masayume/pub/tvk.gif"     
     , "inspire/masayume/pub/valenberg.gif"       , "inspire/masayume/pub/vcs2600.gif"     
     , "inspire/masayume/pub/voxelzelda.gif"      , "inspire/masayume/pub/vucko.gif"     
     , "inspire/masayume/pub/waneella.gif"        , "inspire/masayume/pub/romain-laurent.gif"     
     , "inspire/masayume/pub/yoshi.gif"           , "inspire/masayume/pub/zombiesmile.gif"     
     , "inspire/masayume/pub/wavy.gif"            , "inspire/masayume/pub/SOMA.gif"     
     , "inspire/@CARTOONS/@gif%20animations/0001.gif"     , "inspire/@CARTOONS/@gif%20animations/0002.gif"
     , "inspire/@CARTOONS/@gif%20animations/0003.gif"     , "inspire/@CARTOONS/@gif%20animations/0004.gif"
     , "inspire/@CARTOONS/@gif%20animations/0101.gif"     , "inspire/@CARTOONS/@gif%20animations/0102.gif"
     , "inspire/@CARTOONS/@gif%20animations/0103.gif"     , "inspire/@CARTOONS/@gif%20animations/0104.gif"
     , "inspire/@CARTOONS/@gif%20animations/0105.gif"     , "inspire/@CARTOONS/@gif%20animations/0106.gif"
     , "inspire/@CARTOONS/@gif%20animations/0107.gif"     , "inspire/@CARTOONS/@gif%20animations/0108.gif"
     , "inspire/@CARTOONS/@gif%20animations/0109.gif"     , "inspire/@CARTOONS/@gif%20animations/0110.gif"
     , "inspire/@CARTOONS/@gif%20animations/0111.gif"     , "inspire/@CARTOONS/@gif%20animations/0112.gif"
     , "inspire/@CARTOONS/@gif%20animations/0113.gif"     , "inspire/@CARTOONS/@gif%20animations/0114.gif"
     , "inspire/@CARTOONS/@gif%20animations/0115.gif"     , "inspire/@CARTOONS/@gif%20animations/0116.gif"
     , "inspire/@CARTOONS/@gif%20animations/0117.gif"     , "inspire/@CARTOONS/@gif%20animations/0118.gif"
     , "inspire/@CARTOONS/@gif%20animations/0119.gif"     , "inspire/@CARTOONS/@gif%20animations/0120.gif"
     , "inspire/@CARTOONS/@gif%20animations/0121.gif"     , "inspire/@CARTOONS/@gif%20animations/0122.gif"
     , "inspire/@CARTOONS/@gif%20animations/0123.gif"     , "inspire/@CARTOONS/@gif%20animations/0124.gif"
     , "inspire/@CARTOONS/@gif%20animations/0125.gif"     , "inspire/@CARTOONS/@gif%20animations/0126.gif"
     , "inspire/@CARTOONS/@gif%20animations/0200.gif"     , "inspire/@CARTOONS/@gif%20animations/0201.gif"
     , "inspire/@CARTOONS/@gif%20animations/0202.gif"     , "inspire/@CARTOONS/@gif%20animations/0203.gif"
     , "inspire/@CARTOONS/@gif%20animations/0204.gif"     , "inspire/@CARTOONS/@gif%20animations/0205.gif"
     , "inspire/@CARTOONS/@gif%20animations/0206.gif"     , "inspire/@CARTOONS/@gif%20animations/0207.gif"
     , "inspire/@CARTOONS/@gif%20animations/0208.gif"     , "inspire/@CARTOONS/@gif%20animations/0209.gif"
     , "inspire/@CARTOONS/@gif%20animations/0210.gif"     , "inspire/@CARTOONS/@gif%20animations/0211.gif"
     , "inspire/@CARTOONS/@gif%20animations/0212.gif"     , "inspire/@CARTOONS/@gif%20animations/0213.gif"
     , "inspire/@CARTOONS/@gif%20animations/0214.gif"     , "inspire/@CARTOONS/@gif%20animations/0215.gif"
     , "inspire/@CARTOONS/@gif%20animations/0216.gif"     , "inspire/@CARTOONS/@gif%20animations/0217.gif"
     , "inspire/@CARTOONS/@gif%20animations/0218.gif"     , "inspire/@CARTOONS/@gif%20animations/0219.gif"
     , "inspire/@CARTOONS/@gif%20animations/0220.gif"     , "inspire/@CARTOONS/@gif%20animations/0221.gif"
     , "inspire/@CARTOONS/@gif%20animations/0222.gif"     , "inspire/@CARTOONS/@gif%20animations/0223.gif"
     , "inspire/@CARTOONS/@gif%20animations/0224.gif"     , "inspire/@CARTOONS/@gif%20animations/0225.gif"
     , "inspire/@CARTOONS/@gif%20animations/0226.gif"     , "inspire/@CARTOONS/@gif%20animations/0227.gif"
     , "inspire/@CARTOONS/@gif%20animations/0228.gif"     , "inspire/@CARTOONS/@gif%20animations/0229.gif"
     , "inspire/@CARTOONS/@gif%20animations/0230.gif"     
     , "inspire/@CARTOONS/@gif%20animations/0300.gif"     , "inspire/@CARTOONS/@gif%20animations/0301.gif"
     , "inspire/@CARTOONS/@gif%20animations/0302.gif"     , "inspire/@CARTOONS/@gif%20animations/0303.gif"
     , "inspire/@CARTOONS/@gif%20animations/0304.gif"     , "inspire/@CARTOONS/@gif%20animations/0305.gif"
     , "inspire/@CARTOONS/@gif%20animations/0306.gif"     
     , "inspire/@pixelart/_waneella-001.gif"     , "inspire/@pixelart/_waneella-002.gif"
     , "inspire/@pixelart/_waneella-003.gif"     , "inspire/@pixelart/_waneella-004.gif"
     , "inspire/@pixelart/_waneella-005.gif"     , "inspire/@pixelart/_waneella-006.gif"
     , "inspire/@pixelart/_waneella-007.gif"     , "inspire/@pixelart/_waneella-008.gif"
     , "inspire/@pixelart/_waneella-009.gif"     , "inspire/@pixelart/_waneella-010.gif"
     , "inspire/@pixelart/_waneella-011.gif"     , "inspire/@pixelart/_waneella-012.gif"
     , "inspire/@pixelart/_waneella-013.gif"     , "inspire/@pixelart/_waneella-014.gif"
     , "inspire/@pixelart/_waneella-015.gif"     , "inspire/@pixelart/_waneella-016.gif"
     , "inspire/@pixelart/_waneella-017.gif"     , "inspire/@pixelart/_waneella-018.gif"
     , "inspire/@pixelart/_waneella-019.gif"     , "inspire/@pixelart/_waneella-020.gif"
     , "inspire/@pixelart/_waneella-021.gif"     , "inspire/@pixelart/_waneella-022.gif"
     , "inspire/@pixelart/_waneella-023.gif"     , "inspire/@pixelart/_waneella-024.gif" 
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-001.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-002.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-003.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-004.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-005.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-006.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-007.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-008.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-009.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-010.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-011.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-012.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-013.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-014.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-015.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-016.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-017.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-018.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-019.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-020.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-021.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-022.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-023.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-024.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-025.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-026.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-027.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-028.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-029.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-030.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-031.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-032.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-033.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-034.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-035.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-036.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-037.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-038.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-039.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-040.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-041.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-042.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-043.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-044.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-045.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-046.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-047.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-048.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-049.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-050.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-051.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-052.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-053.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-054.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-055.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-056.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-057.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-058.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-059.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-060.gif"
     , "inspire/@CARTOONS/@gif%20animations/_rDavey-061.gif"     , "inspire/@CARTOONS/@gif%20animations/_rDavey-062.gif"
//     , "inspire/@CARTOONS/@gif%20animations/_rDavey-063.gif"     
     , "inspire/@CARTOONS/@gif%20animations/_retro-001.gif"      , "inspire/@CARTOONS/@gif%20animations/_retro-002.gif"     
     , "inspire/@CARTOONS/@gif%20animations/_retro-003.gif"      , "inspire/@CARTOONS/@gif%20animations/_retro-004.gif"     
     , "inspire/@CARTOONS/@gif%20animations/_retro-005.gif"      , "inspire/@CARTOONS/@gif%20animations/_retro-006.gif"     
     , "inspire/@CARTOONS/@gif%20animations/_retro-007.gif"      , "inspire/@CARTOONS/@gif%20animations/_retro-008.gif"     
     , "inspire/@CARTOONS/@gif%20animations/_retro-009.gif"      , "inspire/@CARTOONS/@gif%20animations/_retro-010.gif"     
     , "inspire/@CARTOONS/@gif%20animations/_retro-011.gif"      , "inspire/@CARTOONS/@gif%20animations/_retro-012.gif"     
     , "inspire/@CARTOONS/@gif%20animations/_retro-013.gif"      , "inspire/@CARTOONS/@gif%20animations/_retro-014.gif"
     , "inspire/@CARTOONS/@gif%20animations/_retro-015.gif"      , "inspire/@CARTOONS/@gif%20animations/_retro-016.gif"
     , "inspire/@CARTOONS/@gif%20animations/_retro-017.gif"      
     , "inspire/@CARTOONS/@gif%20animations/kyoani-001.gif"     
     , "inspire/@CARTOONS/@gif%20animations/ghibli-001.gif"      , "inspire/@CARTOONS/@gif%20animations/ghibli-002.gif"     
     , "inspire/@CARTOONS/@gif%20animations/humor-001.gif"      , "inspire/@CARTOONS/@gif%20animations/humor-002.gif"
     , "inspire/@CARTOONS/@gif%20animations/humor-003.gif"      , "inspire/@CARTOONS/@gif%20animations/humor-004.gif"
     , "inspire/@CARTOONS/@gif%20animations/humor-005.gif"      , "inspire/@CARTOONS/@gif%20animations/humor-006.gif"
     , "inspire/@CARTOONS/@gif%20animations/humor-007.gif"      , "inspire/@CARTOONS/@gif%20animations/humor-008.gif"
     , "inspire/@CARTOONS/@gif%20animations/humor-009.gif"      , "inspire/@CARTOONS/@gif%20animations/humor-010.gif"
     , "inspire/@CARTOONS/@gif%20animations/humor-011.gif"      , "inspire/@CARTOONS/@gif%20animations/humor-012.gif"
     , "inspire/@CARTOONS/@gif%20animations/humor-013.gif"      , "inspire/@CARTOONS/@gif%20animations/humor-014.gif"
     , "inspire/@CARTOONS/@gif%20animations/humor-015.gif"      , "inspire/@CARTOONS/@gif%20animations/humor-016.gif"
     , "inspire/@CARTOONS/@gif%20animations/humor-017.gif"      , "inspire/@CARTOONS/@gif%20animations/humor-018.gif"      
     , "inspire/@CARTOONS/@gif%20animations/humor-019.gif"      , "inspire/@CARTOONS/@gif%20animations/humor-020.gif"      
     , "inspire/@CARTOONS/@gif%20animations/humor-021.gif"      , "inspire/@CARTOONS/@gif%20animations/humor-022.gif"      
     , "inspire/@CARTOONS/@gif%20animations/humor-023.gif"      , "inspire/@CARTOONS/@gif%20animations/humor-024.gif"      
     , "inspire/@CARTOONS/@gif%20animations/wow-001.gif"        , "inspire/@CARTOONS/@gif%20animations/wow-002.gif"
     , "inspire/@CARTOONS/@gif%20animations/wow-003.gif"        , "inspire/@CARTOONS/@gif%20animations/wow-004.gif"
     , "inspire/@CARTOONS/@gif%20animations/wow-005.gif"        , "inspire/@CARTOONS/@gif%20animations/wow-006.gif"
     , "inspire/@CARTOONS/@gif%20animations/wow-007.gif"        , "inspire/@CARTOONS/@gif%20animations/wow-008.gif"
     , "inspire/@CARTOONS/@gif%20animations/wow-009.gif"        , "inspire/@CARTOONS/@gif%20animations/wow-010.gif"
     , "inspire/@CARTOONS/@gif%20animations/wow-011.gif"        , "inspire/@CARTOONS/@gif%20animations/wow-012.gif"
     , "inspire/@CARTOONS/@gif%20animations/wow-013.gif"        , "inspire/@CARTOONS/@gif%20animations/wow-014.gif"
     , "inspire/@CARTOONS/@gif%20animations/wow-015.gif"        , "inspire/@CARTOONS/@gif%20animations/wow-016.gif"
     , "inspire/@CARTOONS/@gif%20animations/wow-017.gif"        , "inspire/@CARTOONS/@gif%20animations/wow-018.gif"
     , "inspire/@CARTOONS/@gif%20animations/wow-019.gif"        , "inspire/@CARTOONS/@gif%20animations/wow-020.gif"
     , "inspire/@CARTOONS/@gif%20animations/wow-015.gif"        , "inspire/@CARTOONS/@gif%20animations/wow-022.gif"
     , "inspire/@CARTOONS/@gif%20animations/wow-023.gif"        , "inspire/@CARTOONS/@gif%20animations/wow-024.gif"
     , "inspire/@CARTOONS/@gif%20animations/wow-025.gif"        , "inspire/@CARTOONS/@gif%20animations/wow-026.gif"

    ];
    
  function getImageTag() {
    var img = '<img src=\"';
    var randomIndex = Math.floor(Math.random() * imageURLs.length);
    img += imageURLs[randomIndex];
    img += '\" alt=\"Some alt text\" width=300 />';
    return img;
  }
