/*
  to add images:
#:~/inspire/@pixelart$ ls -rlt STYLE/tw* | awk '{print ", \"inspire/@pixelart/" $NF "\""}'

*/


  var imageURLs = [
       "inspire/@pixelart/_waneella-001.gif"     , "inspire/@pixelart/_waneella-002.gif"
     , "inspire/@pixelart/_waneella-003.gif"     , "inspire/@pixelart/_waneella-004.gif"
     , "inspire/@pixelart/_waneella-005.gif"     , "inspire/@pixelart/_waneella-006.gif"
     , "inspire/@pixelart/_waneella-007.gif"     , "inspire/@pixelart/_waneella-008.gif"
     , "inspire/@pixelart/_waneella-009.gif"     , "inspire/@pixelart/_waneella-010.gif"
     , "inspire/@pixelart/_waneella-011.gif"     , "inspire/@pixelart/_waneella-012.gif"
     , "inspire/@pixelart/_waneella-013.gif"     , "inspire/@pixelart/_waneella-014.gif"
     , "inspire/@pixelart/_waneella-015.gif"     , "inspire/@pixelart/_waneella-016.gif"
     , "inspire/@pixelart/_waneella-017.gif"     , "inspire/@pixelart/_waneella-018.gif"
     , "inspire/@pixelart/_waneella-019.gif"     , "inspire/@pixelart/_waneella-020.gif"
     , "inspire/@pixelart/_waneella-021.gif"     , "inspire/@pixelart/_waneella-022.gif"
     , "inspire/@pixelart/_waneella-023.jpg"     

     , "inspire/@pixelart/tw-mabius6-01.png"     , "inspire/@pixelart/tw-mabius6-02.png"
     , "inspire/@pixelart/tw-mabius6-03.png"     , "inspire/@pixelart/tw-mabius6-04.png"
     , "inspire/@pixelart/tw-mabius6-05.png"     , "inspire/@pixelart/tw-mabius6-06.png"
     , "inspire/@pixelart/tw-mabius6-07.png"     , "inspire/@pixelart/tw-mabius6-08.png"
     , "inspire/@pixelart/tw-mabius6-09.png"     , "inspire/@pixelart/tw-mabius6-10.png"
     , "inspire/@pixelart/tw-mabius6-11.png"     , "inspire/@pixelart/tw-mabius6-12.png"
     , "inspire/@pixelart/tw-mabius6-13.png"     , "inspire/@pixelart/tw-mabius6-14.png"
     , "inspire/@pixelart/tw-mabius6-15.png"     , "inspire/@pixelart/tw-mabius6-16.png"
     , "inspire/@pixelart/tw-mabius6-17.png"     , "inspire/@pixelart/tw-mabius6-18.png"
     , "inspire/@pixelart/tw-mabius6-19.png"     , "inspire/@pixelart/tw-mabius6-20.png"
     , "inspire/@pixelart/tw-mabius6-21.png"     , "inspire/@pixelart/tw-mabius6-22.png"
     , "inspire/@pixelart/tw-mabius6-23.png"     , "inspire/@pixelart/tw-mabius6-24.png"
     , "inspire/@pixelart/tw-mabius6-25.png"     , "inspire/@pixelart/tw-mabius6-26.png"
     , "inspire/@pixelart/tw-mabius6-27.png"     , "inspire/@pixelart/tw-mabius6-28.png"
     , "inspire/@pixelart/tw-mabius6-29.png"     , "inspire/@pixelart/tw-mabius6-30.png"
     , "inspire/@pixelart/tw-mabius6-31.png"     , "inspire/@pixelart/tw-mabius6-32.png"
     , "inspire/@pixelart/tw-mabius6-33.png"     , "inspire/@pixelart/tw-mabius6-34.png"
     , "inspire/@pixelart/tw-mabius6-35.png"     , "inspire/@pixelart/tw-mabius6-36.png"
     , "inspire/@pixelart/tw-mabius6-37.png"     , "inspire/@pixelart/tw-mabius6-38.png"
     , "inspire/@pixelart/tw-mabius6-39.png"     , "inspire/@pixelart/tw-mabius6-30.png"
     , "inspire/@pixelart/tw-mabius6-41.png"     , "inspire/@pixelart/tw-mabius6-42.png"
     , "inspire/@pixelart/tw-mabius6-43.png"     , "inspire/@pixelart/tw-mabius6-44.png"
     , "inspire/@pixelart/tw-mabius6-45.png"     , "inspire/@pixelart/tw-mabius6-46.png"
     , "inspire/@pixelart/tw-mabius6-47.png"     , "inspire/@pixelart/tw-mabius6-48.png"
     , "inspire/@pixelart/tw-mabius6-49.png"     , "inspire/@pixelart/tw-mabius6-40.png"
     , "inspire/@pixelart/tw-mabius6-51.png"     , "inspire/@pixelart/tw-mabius6-52.png"
     , "inspire/@pixelart/tw-mabius6-53.png"     , "inspire/@pixelart/tw-mabius6-54.png"
     , "inspire/@pixelart/tw-mabius6-55.png"     , "inspire/@pixelart/tw-mabius6-56.png"
     , "inspire/@pixelart/tw-mabius6-57.png"     , "inspire/@pixelart/tw-mabius6-58.png"
     , "inspire/@pixelart/tw-mabius6-59.png"     , "inspire/@pixelart/tw-mabius6-50.png"
     , "inspire/@pixelart/tw-mabius6-61.png"     , "inspire/@pixelart/tw-mabius6-62.png"
     , "inspire/@pixelart/tw-mabius6-63.png"     , "inspire/@pixelart/tw-mabius6-64.png"
     , "inspire/@pixelart/tw-mabius6-65.png"     , "inspire/@pixelart/tw-mabius6-66.png"
     , "inspire/@pixelart/tw-mabius6-67.png"     , "inspire/@pixelart/tw-mabius6-68.png"
     , "inspire/@pixelart/tw-mabius6-69.png"     , "inspire/@pixelart/tw-mabius6-70.png"
     , "inspire/@pixelart/tw-mabius6-71.png"     , "inspire/@pixelart/tw-mabius6-72.png"
     , "inspire/@pixelart/tw-mabius6-73.png"     , "inspire/@pixelart/tw-mabius6-74.png"
     , "inspire/@pixelart/tw-mabius6-75.png"     , "inspire/@pixelart/tw-mabius6-76.jpg"
     , "inspire/@pixelart/tw-mabius6-77.png"     , "inspire/@pixelart/tw-mabius6-78.jpg"
     , "inspire/@pixelart/tw-mabius6-78b.jpg"    , "inspire/@pixelart/tw-mabius6-78.png"
     , "inspire/@pixelart/tw-mabius6-79.png"     , "inspire/@pixelart/tw-mabius6-80.jpg"
     , "inspire/@pixelart/tw-mabius6-81.jpg"     , "inspire/@pixelart/tw-mabius6-82.jpg"
     , "inspire/@pixelart/tw-mabius6-83.png"     , "inspire/@pixelart/tw-mabius6-84.png"
     , "inspire/@pixelart/tw-mabius6-85.png"     , "inspire/@pixelart/tw-mabius6-86.jpg"
     , "inspire/@pixelart/tw-mabius6-87.png"     , "inspire/@pixelart/tw-mabius6-88.jpg"
     , "inspire/@pixelart/tw-mabius6-89.png"     , "inspire/@pixelart/tw-mabius6-90.png"
     , "inspire/@pixelart/tw-mabius6-91.png"     , "inspire/@pixelart/tw-mabius6-92.jpg"
     , "inspire/@pixelart/tw-mabius6-93.png"     , "inspire/@pixelart/tw-mabius6-94.jpg"
     , "inspire/@pixelart/tw-mabius6-95.png"     , "inspire/@pixelart/tw-mabius6-96.png"
     , "inspire/@pixelart/tw-mabius6-97.png"     , "inspire/@pixelart/tw-mabius6-98.png"
     , "inspire/@pixelart/tw-mabius6-97a.png"    , "inspire/@pixelart/tw-mabius6-97b.png"
     , "inspire/@pixelart/tw-mabius6-99.png"     , "inspire/@pixelart/tw-mabius6-100.png"
     , "inspire/@pixelart/tw-mabius6-101.png"    , "inspire/@pixelart/tw-mabius6-102.png"
     , "inspire/@pixelart/tw-mabius6-103.png"    , "inspire/@pixelart/tw-mabius6-104.png"
     , "inspire/@pixelart/tw-mabius6-105.png"    , "inspire/@pixelart/tw-mabius6-106.png"
     , "inspire/@pixelart/tw-mabius6-107.png"    , "inspire/@pixelart/tw-mabius6-108.png"
     , "inspire/@pixelart/tw-mabius6-109.png"    , "inspire/@pixelart/tw-mabius6-110.png"
     , "inspire/@pixelart/tw-mabius6-111.png"    , "inspire/@pixelart/tw-mabius6-112.png"
     , "inspire/@pixelart/tw-mabius6-113.png"    , "inspire/@pixelart/tw-mabius6-114.png"
     , "inspire/@pixelart/tw-mabius6-115.png"    , "inspire/@pixelart/tw-mabius6-116.png"
     , "inspire/@pixelart/tw-mabius6-117.png"    , "inspire/@pixelart/tw-mabius6-118.png"
     , "inspire/@pixelart/tw-mabius6-119.png"    , "inspire/@pixelart/tw-mabius6-110.png"
     , "inspire/@pixelart/tw-mabius6-121.png"    , "inspire/@pixelart/tw-mabius6-122.png"
     , "inspire/@pixelart/tw-mabius6-123.png"    , "inspire/@pixelart/tw-mabius6-124.png"
     , "inspire/@pixelart/tw-mabius6-125.png"    , "inspire/@pixelart/tw-mabius6-126.png"
     , "inspire/@pixelart/tw-mabius6-127.png"    , "inspire/@pixelart/tw-mabius6-128.png"
     , "inspire/@pixelart/tw-mabius6-129.png"    , "inspire/@pixelart/tw-mabius6-130.png"
     , "inspire/@pixelart/tw-mabius6-131.png"    , "inspire/@pixelart/tw-mabius6-132.png"
     , "inspire/@pixelart/tw-mabius6-133.jpg"    , "inspire/@pixelart/tw-mabius6-134.png"
     , "inspire/@pixelart/tw-mabius6-134d.png"   , "inspire/@pixelart/tw-mabius6-134e.png"
     , "inspire/@pixelart/tw-mabius6-135.png"    , "inspire/@pixelart/tw-mabius6-136.png"
     , "inspire/@pixelart/tw-mabius6-137.png"    , "inspire/@pixelart/tw-mabius6-138.png"
     , "inspire/@pixelart/tw-mabius6-137b.png"   , "inspire/@pixelart/tw-mabius6-139b.png"
     , "inspire/@pixelart/tw-mabius6-139.png"    , "inspire/@pixelart/tw-mabius6-140.png"
     , "inspire/@pixelart/tw-mabius6-141.png"    , "inspire/@pixelart/tw-mabius6-142.png"
     , "inspire/@pixelart/tw-mabius6-140.png"    , "inspire/@pixelart/tw-mabius6-141.png"
     , "inspire/@pixelart/tw-mabius6-WF-2WF-01.png"     , "inspire/@pixelart/tw-mabius6-WF-2WF-02.png"
     , "inspire/@pixelart/tw-mabius6-WF-2WF-03.png"     , "inspire/@pixelart/tw-mabius6-WF-2WF-04.png"
     , "inspire/@pixelart/tw-mabius6-WF-2WF-05.png"     , "inspire/@pixelart/tw-mabius6-WF-2WF-06.png"
     , "inspire/@pixelart/tw-mabius6-WF-2WF-07.png"     , "inspire/@pixelart/tw-mabius6-WF-2WF-08.png"
     , "inspire/@pixelart/tw-mabius6-WF-2WF-09.png"     , "inspire/@pixelart/tw-mabius6-WF-2WF-00.png"
     , "inspire/@pixelart/tw-mabius6-WF-2WF-10.png"

     , "inspire/@pixelart/tw-Omegachainoboy-01.png"     , "inspire/@pixelart/tw-Omegachainoboy-02.png"
     , "inspire/@pixelart/tw-Omegachainoboy-03.png"     , "inspire/@pixelart/tw-Omegachainoboy-04.png"
     , "inspire/@pixelart/tw-Omegachainoboy-05.png"     , "inspire/@pixelart/tw-Omegachainoboy-06.jpg"
     , "inspire/@pixelart/tw-Omegachainoboy-07.png"     , "inspire/@pixelart/tw-Omegachainoboy-08.png"
     , "inspire/@pixelart/tw-Omegachainoboy-09.png"     , "inspire/@pixelart/tw-Omegachainoboy-10.png"
     , "inspire/@pixelart/tw-Omegachainoboy-11.png"     , "inspire/@pixelart/tw-Omegachainoboy-12.png"
     , "inspire/@pixelart/tw-Omegachainoboy-13.png"     , "inspire/@pixelart/tw-Omegachainoboy-14.png"
     , "inspire/@pixelart/tw-Omegachainoboy-15.png"     , "inspire/@pixelart/tw-Omegachainoboy-16.png"
     , "inspire/@pixelart/tw-Omegachainoboy-17.png"     , "inspire/@pixelart/tw-Omegachainoboy-18.png"
     , "inspire/@pixelart/tw-Omegachainoboy-19.png"     , "inspire/@pixelart/tw-Omegachainoboy-20.png"
     , "inspire/@pixelart/tw-Omegachainoboy-21.png"     , "inspire/@pixelart/tw-Omegachainoboy-22.png"
     , "inspire/@pixelart/tw-Omegachainoboy-23.png"     , "inspire/@pixelart/tw-Omegachainoboy-24.png"
     , "inspire/@pixelart/tw-Omegachainoboy-25.png"     , "inspire/@pixelart/tw-Omegachainoboy-26.png"
     , "inspire/@pixelart/tw-Omegachainoboy-27.png"     , "inspire/@pixelart/tw-Omegachainoboy-28.png"
     , "inspire/@pixelart/tw-Omegachainoboy-29.png"     , "inspire/@pixelart/tw-Omegachainoboy-30.png"
     , "inspire/@pixelart/tw-Omegachainoboy-31.png"     , "inspire/@pixelart/tw-Omegachainoboy-32.png"
     , "inspire/@pixelart/tw-Omegachainoboy-33.png"     , "inspire/@pixelart/tw-Omegachainoboy-34.png"
     , "inspire/@pixelart/tw-Omegachainoboy-35.png"     , "inspire/@pixelart/tw-Omegachainoboy-36.png"
     , "inspire/@pixelart/tw-Omegachainoboy-37.png"     , "inspire/@pixelart/tw-Omegachainoboy-38.png"
     , "inspire/@pixelart/tw-Omegachainoboy-39.png"     , "inspire/@pixelart/tw-Omegachainoboy-30.png"
     , "inspire/@pixelart/tw-Omegachainoboy-41.png"     , "inspire/@pixelart/tw-Omegachainoboy-42.png"
     , "inspire/@pixelart/tw-Omegachainoboy-43.png"     , "inspire/@pixelart/tw-Omegachainoboy-44.png"
     , "inspire/@pixelart/tw-Omegachainoboy-45.png"     , "inspire/@pixelart/tw-Omegachainoboy-46.png"
     , "inspire/@pixelart/tw-Omegachainoboy-47.png"     , "inspire/@pixelart/tw-Omegachainoboy-48.png"
     , "inspire/@pixelart/tw-Omegachainoboy-49.png"     , "inspire/@pixelart/tw-Omegachainoboy-40.png"
     , "inspire/@pixelart/tw-Omegachainoboy-51.png"     , "inspire/@pixelart/tw-Omegachainoboy-52.png"
     , "inspire/@pixelart/tw-Omegachainoboy-53.png"     , "inspire/@pixelart/tw-Omegachainoboy-54.png"
     , "inspire/@pixelart/tw-Omegachainoboy-55.png"     , "inspire/@pixelart/tw-Omegachainoboy-56.png"
     , "inspire/@pixelart/tw-Omegachainoboy-57.png"     , "inspire/@pixelart/tw-Omegachainoboy-58.png"
     , "inspire/@pixelart/tw-Omegachainoboy-59.png"     , "inspire/@pixelart/tw-Omegachainoboy-60.png"
     , "inspire/@pixelart/tw-Omegachainoboy-61.png"     , "inspire/@pixelart/tw-Omegachainoboy-62.png"
     , "inspire/@pixelart/tw-Omegachainoboy-63.png"     , "inspire/@pixelart/tw-Omegachainoboy-64.png"
     , "inspire/@pixelart/tw-Omegachainoboy-65.png"     , "inspire/@pixelart/tw-Omegachainoboy-66.png"
     , "inspire/@pixelart/tw-Omegachainoboy-67.png"     , "inspire/@pixelart/tw-Omegachainoboy-68.png"
     , "inspire/@pixelart/tw-Omegachainoboy-69.png"     , "inspire/@pixelart/tw-Omegachainoboy-70.png"
     , "inspire/@pixelart/tw-Omegachainoboy-71.png"     , "inspire/@pixelart/tw-Omegachainoboy-72.png"
     , "inspire/@pixelart/tw-Omegachainoboy-73.png"     , "inspire/@pixelart/tw-Omegachainoboy-74.png"
     , "inspire/@pixelart/tw-Omegachainoboy-75.png"     

    ];
    
  function getImageTag() {
    var img = '<img src=\"';
    var randomIndex = Math.floor(Math.random() * imageURLs.length);
    img += imageURLs[randomIndex];
    img += '\" alt=\"Some alt text\" width=300 />';
    return img;
  }
